In [1]:
from sklearn.datasets import fetch_20newsgroups

c:\python36\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216, got 192
  return f(*args, **kwds)


In [2]:
twenty_train = fetch_20newsgroups(subset='train', shuffle=True)

In [3]:
dir(twenty_train)

['DESCR', 'data', 'description', 'filenames', 'target', 'target_names']

In [4]:
twenty_train.target

array([7, 4, 4, ..., 3, 1, 8])

In [6]:
twenty_train.target_names

['alt.atheism',
 'comp.graphics',
 'comp.os.ms-windows.misc',
 'comp.sys.ibm.pc.hardware',
 'comp.sys.mac.hardware',
 'comp.windows.x',
 'misc.forsale',
 'rec.autos',
 'rec.motorcycles',
 'rec.sport.baseball',
 'rec.sport.hockey',
 'sci.crypt',
 'sci.electronics',
 'sci.med',
 'sci.space',
 'soc.religion.christian',
 'talk.politics.guns',
 'talk.politics.mideast',
 'talk.politics.misc',
 'talk.religion.misc']

In [9]:
from sklearn.feature_extraction.text import CountVectorizer
count_vect = CountVectorizer()

In [10]:
X_train_counts=count_vect.fit_transform(twenty_train.data)

In [14]:
X_train_counts.shape

(11314, 130107)

In [15]:
print(X_train_counts)

  (0, 86580)	1
  (0, 128420)	1
  (0, 35983)	1
  (0, 35187)	1
  (0, 66098)	1
  (0, 114428)	1
  (0, 78955)	1
  (0, 94362)	1
  (0, 76722)	1
  (0, 57308)	1
  (0, 62221)	1
  (0, 128402)	2
  (0, 67156)	1
  (0, 123989)	1
  (0, 90252)	1
  (0, 63363)	1
  (0, 78784)	1
  (0, 96144)	1
  (0, 128026)	1
  (0, 109271)	1
  (0, 51730)	1
  (0, 86001)	1
  (0, 83256)	1
  (0, 113986)	1
  (0, 37565)	1
  :	:
  (11313, 87626)	1
  (11313, 30044)	1
  (11313, 76377)	1
  (11313, 119714)	1
  (11313, 47982)	1
  (11313, 28146)	2
  (11313, 88363)	2
  (11313, 56283)	1
  (11313, 111695)	1
  (11313, 90252)	1
  (11313, 51730)	1
  (11313, 68766)	1
  (11313, 89860)	1
  (11313, 80638)	1
  (11313, 4605)	1
  (11313, 76032)	1
  (11313, 89362)	1
  (11313, 90379)	1
  (11313, 64095)	1
  (11313, 95162)	1
  (11313, 87620)	1
  (11313, 111322)	1
  (11313, 85354)	1
  (11313, 50527)	2
  (11313, 56979)	2


In [16]:
from sklearn.feature_extraction.text import TfidfTransformer
tfidf_transformer = TfidfTransformer()
X_train_tfidf = tfidf_transformer.fit_transform(X_train_counts)
X_train_tfidf.shape

(11314, 130107)

In [17]:
print(X_train_tfidf)

  (0, 56979)	0.0574701540748513
  (0, 75358)	0.3538350134970617
  (0, 123162)	0.25970902457356887
  (0, 118280)	0.21186807208281694
  (0, 50527)	0.05461428658858725
  (0, 124031)	0.10798795154169123
  (0, 85354)	0.03696978508816317
  (0, 114688)	0.06214070986309587
  (0, 111322)	0.019156718024950434
  (0, 123984)	0.036854292634593756
  (0, 37780)	0.3813389125949312
  (0, 68532)	0.07325812342131598
  (0, 114731)	0.1444727551278406
  (0, 87620)	0.0356718631408158
  (0, 95162)	0.03447138409326312
  (0, 64095)	0.035420924271313554
  (0, 98949)	0.16068606055394935
  (0, 90379)	0.01992885995664587
  (0, 118983)	0.03708597805061915
  (0, 89362)	0.06521174306303765
  (0, 79666)	0.10936401252414275
  (0, 40998)	0.07801368196918111
  (0, 92081)	0.09913274493911224
  (0, 76032)	0.01921946305222309
  (0, 4605)	0.06332603952480324
  :	:
  (11313, 110796)	0.23484539429757872
  (11313, 106209)	0.10108674247893115
  (11313, 31386)	0.11766332475169257
  (11313, 124103)	0.08435681444533488
  (11313, 116

# MultinomialNB Naive Bayes

In [19]:
from sklearn.naive_bayes import MultinomialNB
clf=MultinomialNB().fit(X_train_tfidf,twenty_train.target)


In [27]:
from sklearn.pipeline import Pipeline
clf_pipeline = Pipeline([('vect', CountVectorizer()),
('tfidf', TfidfTransformer()),
('clf', MultinomialNB())])

In [28]:
text_clf = clf_pipeline.fit(twenty_train.data, twenty_train.target)

In [29]:
import numpy as np
twenty_test = fetch_20newsgroups(subset='test', shuffle=True)

In [32]:
dir(twenty_test)

['DESCR', 'data', 'description', 'filenames', 'target', 'target_names']

In [33]:
twenty_test.target

array([ 7,  5,  0, ...,  9,  6, 15])

In [34]:
predicted = text_clf.predict(twenty_test.data)

In [35]:
np.mean(predicted == twenty_test.target)

0.7738980350504514

# Support Vector Machines (SVM)

In [36]:
from sklearn.linear_model import SGDClassifier
text_clf_svm = Pipeline([('vect', CountVectorizer()),
('tfidf', TfidfTransformer()),
('clf-svm', SGDClassifier(loss='hinge',penalty='l2',alpha=1e-3, n_iter=5, random_state=42))])

In [37]:
text_clf_svm=text_clf_svm.fit(twenty_train.data, twenty_train.target)

In [38]:
predicted_svm=text_clf_svm.predict(twenty_test.data)

In [39]:
np.mean(predicted_svm == twenty_test.target)

0.8238183749336165

# Grid Search

# Naive Bayes With Grid Search

In [40]:
from sklearn.model_selection import GridSearchCV
parameters = {'vect__ngram_range': [(1, 1), (1, 2)],'tfidf__use_idf': (True, False),'clf__alpha': (1e-2, 1e-3)}

vect__ngram_range; here we are telling to use unigram and bigrams and choose the one which is optimal.
Next, we create an instance of the grid search by passing the classifier, parameters and n_jobs=-1 which tells to use multiple cores from user machine.

In [41]:
gs_clf = GridSearchCV(text_clf, parameters, n_jobs=-1)
gs_clf = gs_clf.fit(twenty_train.data, twenty_train.target)


In [42]:
gs_clf.best_score_,gs_clf.best_params_

(0.9067526957751458,
 {'clf__alpha': 0.01, 'tfidf__use_idf': True, 'vect__ngram_range': (1, 2)})

# SVM With Grid Search

In [46]:
parameters_svm = {'vect__ngram_range': [(1, 1), (1, 2)],
'tfidf__use_idf': (True, False),
'clf-svm__alpha': (1e-2, 1e-3),
}

In [47]:
gs_clf_svm = GridSearchCV(text_clf_svm, parameters_svm, n_jobs=-1)
gs_clf_svm = gs_clf_svm.fit(twenty_train.data, twenty_train.target)

In [48]:
gs_clf_svm.best_score_,gs_clf_svm.best_params_

(0.8979140887396146,
 {'clf-svm__alpha': 0.001,
  'tfidf__use_idf': True,
  'vect__ngram_range': (1, 2)})

# Removing stop words:

# With Naive Bayes

In [49]:
text_clf = Pipeline([('vect', CountVectorizer(stop_words='english')),('tfidf', TfidfTransformer()),('clf', MultinomialNB()),])

In [51]:
without_stopword=text_clf.fit(twenty_train.data, twenty_train.target)

In [52]:
predict_withoutstopword=without_stopword.predict(twenty_test.data)

In [53]:
np.mean(predict_withoutstopword == twenty_test.target)

0.8169144981412639

In [55]:
predict_withoutstopword

array([ 7,  1,  0, ...,  9,  3, 15])

# With SVM

In [56]:
text_clf_SVM = Pipeline([('vect1', CountVectorizer(stop_words='english')),('tfidf1', TfidfTransformer()),('clf1', SGDClassifier(loss='hinge',penalty='l2',alpha=0.001, n_iter=5, random_state=42)),])

In [58]:
new_svm=text_clf_SVM.fit(twenty_train.data,twenty_train.target)

In [61]:
predict_new_svm=new_svm.predict(twenty_test.data)

In [62]:
np.mean(predict_new_svm == twenty_test.target)

0.8224907063197026